### ISSUE TITLE
myextension@0.1.0 is not compatible with the current JupyterLab

### ISSUE THREAD

**Issue by SonakshiGrover** [jupyterlab/extension-examples#110]
Hello,

I just tried creating a new extension using the hello world template and it giving me - **myextension@0.1.0 is not compatible with the current JupyterLab**. 

It was until yesterday working for me. Could you please look into this? Is the cookiecutter repo undergoing any beta release? I didn't make any upgrades to jupyterlab.

**Comment by blink1073** [comment]
Hi @SonakshiGrover, yes, we are updating the cookiecutter for 3.0 compatibility, please use `cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts --checkout v2.0` for now.

**Comment by jasongrout** [comment]
Oops. I just pushed a 3.0 branch, and reverted master back to 2.0, so we don't break everyone.

**Comment by jasongrout** [comment]
So now, you can go back to doing `cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts` for jlab 2.

Steve, we can push our changes to the `3.0` branch.

**Comment by SonakshiGrover** [comment]
Cool. Thanks for confirming.
