### ISSUE TITLE
[DISCUSS] Flatten the examples folder structure

### ISSUE THREAD

**Issue by echarles** [jupyterlab/extension-examples#114]
I remember when we have introduced the nested structure for the example. The goal was to list high level concerns and implement a few examples by concern.

Looking back at this and also in the light of other projects having such example repositories, I believe we should roll back and flatten the structure. Just one folder per example with a relevant name. The concern constraint does no scale.

I can open a PR for this if we get enough buy-in on this issue.

WDYT?

**Comment by jtpio** [comment]
Sounds good, as this would also make the examples in nested folders (such as `advanced`) more visible from the GitHub file explorer.

**Comment by blink1073** [comment]
I agree with flattening

**Comment by echarles** [comment]
Sounds like we will flatten. I will work on this after the 3.0 branch is merged in master.

**Comment by echarles** [comment]
Thx a lot @fcollonval and @jtpio . I can remove this from my todo...

Minor comment: The README still contains nested content and also non-alphabetical sorted entries. Do you want me to open a PR to update it?

```
Hello World
Signals
Datagrid
Command Palette
Commands
Launcher
Main Menu
Settings
State
React Widget
Widgets
Log Messages
Custom Log Console
Context Menu
Kernel Output
Kernel Messaging
Server Hello World
```

**Comment by fcollonval** [comment]
Hey @echarles you are welcome.
As you wish, some links are broken in READMEs. So this can be included in the same PR. If you have time before tomorrow be my guess. Otherwise I'll push a PR tomorrow morning.
