### ISSUE TITLE
Add CodeMirror examples for Lab 3

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/extension-examples#129]
Over on core, I promised to do some examples of doing things with CodeMirror in the federated context:
- adding a mode (probably a [simple](https://codemirror.net/demo/simplemode.html) mode)
- adding a gutter
- adding marks

comes from:
- https://github.com/jupyterlab/jupyterlab/issues/9124

**Comment by bollwyvl** [comment]
Starting this now... should have a PR to shop during the sprints tomorrow!

**Comment by fcollonval** [comment]
Closing to focus on Lab 4 and later
