### ISSUE TITLE
new kernel with a specific working directory

### ISSUE THREAD

**Issue by christophe33** [jupyterlab/extension-examples#131]
Hello everybody, 
I'm developing an extension with two different kernels, the front-end kernel and a second kernel to execute the front-end specific cell code. The second kernel is launched when you create or open a notebook in jupyterlab.

my problem : the front-end kernel and the second kernel do not always have the same working directory..
When I work with a notebook that is in the same directory as the command that launches jupyterlab, no problem, but if I change directory in the file explorer of jupyterlab and I launch a second kernel its working directory is different from the new directory

my wish  : I would like the second kernel to have the same working-directory as the front-end. 

Can you help me ?
thank's

**Comment by fcollonval** [comment]
The purpose of this repository is to describe how to use JupyterLab API. As this request is about adding not existing feature, it will be closed. But you can definitely ask on the [Gitter chat](https://gitter.im/jupyterlab/jupyterlab) or on the [Jupyter forum](discourse.jupyter.org/) for pointers.
