### ISSUE TITLE
ValueError: "D:\react_ts\test-demo" is not a valid npm package

### ISSUE THREAD

**Issue by zz23333** [jupyterlab/extension-examples#135]
1  im using the `cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts` to generate a jupyterlab extension package,then i succeeded in generating a package named `current-path`
2   i  tried to `cd D:\react_ts\current-path`  and install this widget as an extension using command `jupyter labextension install .`, then i got the error `ValueError: "D:\react_ts\test-demo" is not a valid npm package`, and `jlpm && jlpm build` is normal

so im confused, my current path is  `D:\react_ts\current-path` , `D:\react_ts\test-demo` was the extension i installed before, why i got this error? this is my error log .   i would be grateful for your answer

`[LabBuildApp] Building in d:\anaconda\envs\jupyter-lab\share\jupyter\lab
[LabBuildApp] Node v12.18.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (build:dev:minimize)
[LabBuildApp] > "D:\Program Files\node-v12.18.0-win-x64\npm.CMD" pack D:\react_ts\test-demo
[LabBuildApp] 
> test-demo@0.1.0 prepare D:/react_ts/test-demo
> jlpm run clean && jlpm run build

yarn run v1.21.1
$ rimraf lib tsconfig.tsbuildinfo
D:\react_ts\test-demo\node_modules\rimraf\bin.js:47
      throw er
      ^

[Error: EPERM: operation not permitted, unlink 'D:\react_ts\test-demo\lib\AlgInfoPage.d.ts'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'D:\\react_ts\\test-demo\\lib\\AlgInfoPage.d.ts'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-demo@0.1.0 prepare: `jlpm run clean && jlpm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-demo@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhaotaod\AppData\Roaming\npm-cache\_logs\2020-12-01T09_04_16_982Z-debug.log

[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "d:\anaconda\envs\jupyter-lab\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "d:\anaconda\envs\jupyter-lab\lib\site-packages\jupyterlab\labapp.py", line 138, in start
    raise e

[LabBuildApp]   File "d:\anaconda\envs\jupyter-lab\lib\site-packages\jupyterlab\labapp.py", line 135, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "d:\anaconda\envs\jupyter-lab\lib\site-packages\jupyterlab\commands.py", line 461, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "d:\anaconda\envs\jupyter-lab\lib\site-packages\jupyterlab\commands.py", line 643, in build
    clean=clean_staging

[LabBuildApp]   File "d:\anaconda\envs\jupyter-lab\lib\site-packages\jupyterlab\commands.py", line 1135, in _populate_staging
    'local_extensions')

[LabBuildApp]   File "d:\anaconda\envs\jupyter-lab\lib\site-packages\jupyterlab\commands.py", line 1267, in _update_local
    info = self._extract_package(source, tempdir)

[LabBuildApp]   File "d:\anaconda\envs\jupyter-lab\lib\site-packages\jupyterlab\commands.py", line 1579, in _extract_package
    raise ValueError(msg % source)

[LabBuildApp] ValueError: "D:\react_ts\test-demo" is not a valid npm package

[LabBuildApp] Exiting application: JupyterLab
`

**Comment by fcollonval** [comment]
@zz23333 Unfortunately tools like npm are not as robust on Windows.

The relevant error in your log is 

```
EPERM: operation not permitted, unlink 'D:\react_ts\test-demo\lib\AlgInfoPage.d.ts'
```

To translate it in something more human: Permission error - unable to remove file `D:\react_ts\test-demo\lib\AlgInfoPage.d.ts`

My best guess is to retry. On Windows Permission error on deletion can be triggered by anti-virus software that are locking files a bit too long (they have a hard time with Javascript development because of the number of files involved). If you have the possibility and the appetite to learn, I would advice to develop on Windows Subsystem for Linux (aka running linux from within windows) using VS Code (https://code.visualstudio.com/docs/remote/wsl). Or using raw docker if you are familiar with that. This will definitely smooth your experience.

**Comment by zz23333** [comment]
> @zz23333 Unfortunately tools like npm are not as robust on Windows.
> 
> The relevant error in your log is
> 
> ```
> EPERM: operation not permitted, unlink 'D:\react_ts\test-demo\lib\AlgInfoPage.d.ts'
> ```
> 
> To translate it in something more human: Permission error - unable to remove file `D:\react_ts\test-demo\lib\AlgInfoPage.d.ts`
> 
> My best guess is to retry. On Windows Permission error on deletion can be triggered by anti-virus software that are locking files a bit too long (they have a hard time with Javascript development because of the number of files involved). If you have the possibility and the appetite to learn, I would advice to develop on Windows Subsystem for Linux (aka running linux from within windows) using VS Code (https://code.visualstudio.com/docs/remote/wsl). Or using raw docker if you are familiar with that. This will definitely smooth your experience.

thanks a lot! after retrying `jupyter labextension install .`, everything seems normal. also, i have a virtual machine with linux(ubuntu 20.04), When I run into problems with the windows system, I also try linux again. 
thanks for your advice!

**Comment by fcollonval** [comment]
Glad it helps
