### ISSUE TITLE
Example on how to add an element between toolbar of the notebook and first cell of the notebook

### ISSUE THREAD

**Issue by pacospace** [jupyterlab/extension-examples#138]
Hi everybody,

I'm looking for an example on how to add an element between menu bar of the notebook and first cell of the notebook.

Currently, the extension has an extension button in the menu bar of the notebook that opens a dialog to allow the user to do something. You can find it in https://github.com/thoth-station/jupyterlab-requirements.

Instead of opening a dialog, I would like to have an element that shows the UI interaction directly in the notebook, specifically between the menu bar of the notebook and the first cell. 

I could not find a way to reuse jupyterlab packages, help is really appreciated.

**Comment by jasongrout** [comment]
When you say "menu bar", I assume you mean the notebook toolbar with buttons at the top of the notebook inside the notebook tab, not the menu bar at the top of the application.

The notebook component assumes that the layout of the widget is the toolbar, followed by the notebook content (with the first cell at the top, etc.). If you want to change the basic structure of the layout of the notebook widget, it's probably best to create a new notebook viewer, use whatever pieces of the existing notebook viewer you want, and create that space that you want in the viewer.

Alternatively, you can create a UX over in the notebook property inspector, with the other UX elements for changing notebook metadata. It would be in a side panel, but that is a part of the application that is explicitly designed for inserting your own UX for controlling notebook metadata.

**Comment by pacospace** [comment]
> When you say "menu bar", I assume you mean the notebook toolbar with buttons at the top of the notebook inside the notebook tab, not the menu bar at the top of the application.
> 

Correct, Thanks @jasongrout sorry for my bad description :+1: 

> The notebook component assumes that the layout of the widget is the toolbar, followed by the notebook content (with the first cell at the top, etc.). If you want to change the basic structure of the layout of the notebook widget, it's probably best to create a new notebook viewer, use whatever pieces of the existing notebook viewer you want, and create that space that you want in the viewer.
> 
> Alternatively, you can create a UX over in the notebook property inspector, with the other UX elements for changing notebook metadata. It would be in a side panel, but that is a part of the application that is explicitly designed for inserting your own UX for controlling notebook metadata.

Great, thank you very much for the options and explanation @jasongrout! :100: 

Option 2 seems more interesting and more in line with the goal of the extension that embed the dependenices of the notebook in the notebook metadata for reusability.

**Comment by pacospace** [comment]
> > When you say "menu bar", I assume you mean the notebook toolbar with buttons at the top of the notebook inside the notebook tab, not the menu bar at the top of the application.
> 
> Correct, Thanks @jasongrout sorry for my bad description 
> 
> > The notebook component assumes that the layout of the widget is the toolbar, followed by the notebook content (with the first cell at the top, etc.). If you want to change the basic structure of the layout of the notebook widget, it's probably best to create a new notebook viewer, use whatever pieces of the existing notebook viewer you want, and create that space that you want in the viewer.
> > Alternatively, you can create a UX over in the notebook property inspector, with the other UX elements for changing notebook metadata. It would be in a side panel, but that is a part of the application that is explicitly designed for inserting your own UX for controlling notebook metadata.
> 
> Great, thank you very much for the options and explanation @jasongrout! 
> 
> Option 2 seems more interesting and more in line with the goal of the extension that embed the dependenices of the notebook in the notebook metadata for reusability.

Is there an example about option 2? @jasongrout Thank you in advance!!

**Comment by fcollonval** [comment]
@pacospace You may be interested by https://github.com/jupytercalpoly/jupyterlab-pkginstaller - although it targets JupyterLab 1, it is close to your use case.

Another example of extension adding a tool in the notebook panel is the celltag one: https://github.com/jupyterlab/jupyterlab/blob/master/packages/celltags-extension/src/index.ts

**Comment by pacospace** [comment]
> @pacospace You may be interested by https://github.com/jupytercalpoly/jupyterlab-pkginstaller - although it targets JupyterLab 1, it is close to your use case.
> 
> Another example of extension adding a tool in the notebook panel is the celltag one: https://github.com/jupyterlab/jupyterlab/blob/master/packages/celltags-extension/src/index.ts

Thanks @fcollonval, I ll look into those for better user experience for the new extension.

**Comment by NoobMaster1999** [comment]
@fcollonval can I add some changes in UX for adding an element in tool bar??

**Comment by fcollonval** [comment]
There is one example you can look at for adding an item to the toolbar: https://github.com/jupyterlab/extension-examples/tree/master/toolbar-button

Note: This request is about using a new feature that adds a panel below the toolbar and before the main widget.
https://jupyterlab.readthedocs.io/en/latest/api/classes/apputils.mainareawidget-1.html#contentheader

**Comment by fcollonval** [comment]
Closing as addressed by https://github.com/jupyterlab/extension-examples/tree/master/contentheader
