### ISSUE TITLE
Issue with IFileBrowserFactory and ICommandPalette

### ISSUE THREAD

**Issue by danny95333** [jupyterlab/extension-examples#140]
I encounter an error and blocked when developed my jupyterlab extension and tried to reproduce it with the official jlab extension example. 
For this [extension-examples/launcher](https://github.com/jupyterlab/extension-examples/tree/6f527393a7185ec24cf72369d091c5c8eac0e518/launcher): 
I found that if I add ICommandPalette to the requires like :
```
  requires: [IFileBrowserFactory, ICommandPalette],
  optional: [ILauncher, IMainMenu],
```
instead of:
```
  requires: [IFileBrowserFactory],
  optional: [ILauncher, IMainMenu, ICommandPalette],
```
The rest of the code is **identical**, the plugin will be failed to activate and console shows:
```
Plugin 'launcher' failed to activate.
TypeError: launcher.add is not a function
    at activate (index.js:48)
    at jlab_core.ec15f8c091a46864d4c7.js:formatted:59045
    at async Promise.all (:8888/lab/workspaces/index 101)
```
So seems that ICommandPalette cannot be in 'requires' along with IFileBrowserFactory.
So the **Question** is, for my use case: When click on this command (from command palette and in menu.fileMenu)then I can get opened file(.py, .md, .ipynb ..) local path. I have done the most part of this extension but currently blocked by how to retrieve the current opened file path in the code block:
```
commands.addCommand(command, {
      label: 'xxx',
      caption: 'xxx,
      icon: args => (args['isPalette'] ? null : icon),
      execute: async args => {
         ...
```
I was thinking that something like this:
```
const extension: JupyterFrontEndPlugin<void> = {
  id: 'main-menu',
  autoStart: true,
  requires: [ICommandPalette, IMainMenu, IFileBrowserFactory],
  activate: (
    app: JupyterFrontEnd,
    browserFactory: IFileBrowserFactory,
    palette: ICommandPalette,
    mainMenu: IMainMenu,
    trans: ITranslator
  ) => {
commands.addCommand(command, {
      label: 'xxxx',
      caption: 'xxxx',
      icon: args => (args['isPalette'] ? null : icon),
      execute: async args => {
         const path = browserFactory.defaultBrowser.model.path;
         console.log(path);
```
But like I mentioned at the very beginning, I cannot make IFileBrowserFactory and ICommandPalette at 'requires' field at the same time. any idea for how to achieve above functionality?

**Comment by jasongrout** [comment]
The arguments to the `activate` function are the `requires` services, then the `optional` services, in order. When you moved the command palette to the requires, you changed the order of the services passed into your activate function. You need to also change the order of the parameters in your activate function arguments.

For example, with your change:

```
  requires: [IFileBrowserFactory, ICommandPalette],
  optional: [ILauncher, IMainMenu],
```
the order of parameters to the activate function would be `IFileBrowserFactory, ICommandPalette, ILauncher, IMainMenu`

**Comment by jasongrout** [comment]
See the documentation for the activate function at https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#application-plugins

**Comment by danny95333** [comment]
Thanks for your quick reply!! That helps, dont know the order things before.
Another following question: Seems that the 
```
browserFactory.defaultBrowser.model.path
```
will only provide the directory path, not the file path. If I have opened a test.ipynb in the current file browser which locate in 
```
/User/danny/example/test.ipynb
```
Above code will only return the path: 
```
example
```
expected full absolute path or at least relative path.
Do you know how to retrieve the full file path(include filename) for the current opened file in the browser.

**Comment by jasongrout** [comment]
All file access in JupyterLab works relative to the root server directory.

The server sometimes (optionally) knows the server root directory: https://github.com/jupyterlab/jupyterlab/blob/b4db7f03d2ad0b91a9c8c252c56ae5e4a9408fbb/packages/application/src/frontend.ts#L337-L362

**Comment by danny95333** [comment]
relative path is ok, but how can I retrieve the file name at least. For my customized command, wants to move this file(opened in the file browser/in current tab) to some where else. Without the file name, my python backend code cannot locate this file.
Logic might be similar to Download command in the file menu, I need to locate this opened file(retrieve the path) when execute this command.

**Comment by danny95333** [comment]
nvm, issue resolved! Thanks for your help.
