### ISSUE TITLE
Error occurs when running jupyterlab-extension-example due to company network security policy

### ISSUE THREAD

**Issue by KevinRyu** [jupyterlab/extension-examples#164]
Hello,

I’m testing jupyterlab-extension-example within my company’s secure network.
The following websites that are blocked from access due to the company’s security policy.

https://registry.npmjs.org/embedme

**

Perhaps unblocking a website is almost impossible.

**

Question
1. An error occurs during execution as shown below. Is it possible to skip or disable this error part?

2. Or, after running this example in a non-blocked network environment, can the created extension be installed in jupyterlab in the above-mentioned blocking environment?

Please help.

============= error message ====================
Run this command for Launcher example : python -m pip install -e .
…
Complete output (41 lines):
running develop
running jsdeps
Installing build dependencies with npm. This may take a while…
> jlpm install
yarn install v1.21.1
info No lockfile found.
[1/4] Resolving packages…
error An unexpected error occurred: “https://registry.npmjs.org/embedme”:
Request “https://registry.npmjs.org/embedme”\ returned a 403".
info If you think this is a bug, please open a bug report with the information provided in …

**Comment by fcollonval** [comment]
Hey @KevinRyu 

Developping for JupyterLab requires to have access to Python and NodeJS packages repositories. If your company is blocking the public repositories, you will need to request either to open access to them or the proxy parameters to access the internet or to get access to some internal mirrors of those repositories.

Then you wil have to set the appropriate settings to use a non-default package repositories:
* NodeJS: 
  * https://docs.npmjs.com/cli/v7/using-npm/config#proxy
  * https://docs.npmjs.com/cli/v7/using-npm/config#registry
* Python pip: 
  * https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server
  * https://pip.pypa.io/en/stable/user_guide/ - look for index url

**Comment by KevinRyu** [comment]
Hi.

Thanks for your reply.
As you mentioned, I already set proxy and can access pip repository and
npm. But while in progress setup.py, register.npmjs.org only not allowed.
So, I don"t know about the function  of this registry site. But, I wonder
the registry site access can be skipped If I can download or prepare before
running setup.py. You said it is not possible, right?


2021년 6월 17일 (목) 오후 4:39, Frédéric Collonval ***@***.***>님이
작성:

**Comment by fcollonval** [comment]
You probably need to set the proxy for `yarn` too: https://www.jhipster.tech/configuring-a-corporate-proxy/

> JupyterLab is using `yarn` instead of `npm` as nodejs package manager.

**Comment by KevinRyu** [comment]
Hi. Thanks.

I already set proxy for both yarn and npm.
Error was not solved...
Can you guide how to set proxy in this case?
I want to check my setting is ok.

2021년 6월 18일 (금) 오후 3:37, Frédéric Collonval ***@***.***>님이
작성:

**Comment by KevinRyu** [comment]
> You probably need to set the proxy for `yarn` too: https://www.jhipster.tech/configuring-a-corporate-proxy/
> 
> > JupyterLab is using `yarn` instead of `npm` as nodejs package manager.

Thank you very much. I will check my proxy setting again.

**Comment by fcollonval** [comment]
Coding this one as answered.
@KevinRyu don't hesitate to reopen, if you have additional information.
