### ISSUE TITLE
Add simple encryption extension

### ISSUE THREAD

**Issue by AdryAqil** [jupyterlab/extension-examples#165]
Hi all, I'm trying to create an encryption extension using [Crypto-ts](https://github.com/hmoog/crypto-ts). The idea is create two new button at toolbar that will encrypt and decrypt selected cell with password access. However, I'm having trouble accessing the content of the cell.

Here a snippet of the encryption code
![Untitled1](https://user-images.githubusercontent.com/78016567/122696466-aec3b480-d275-11eb-8d0c-eb9639270335.png)

I need to change the string, 'some message', to what is in the content of the cell and preferably replace it with the encrypted text. Then, the encrypted text will decrypt when button decrypt is clicked. I researched a bit found a slightly different approach to select the content of the cell by highlighting it before encrypt it by using [getInitialQuery](https://github.com/jupyterlab/jupyterlab/blob/a12457ee7aff6745afe53c431b45315c3193aa1a/packages/documentsearch/src/providers/notebooksearchprovider.ts#L38-L45). (I think that what it does?)(I apologize if it not)

Also, the issue to prompt a password every time encrypt and decrypt is clicked. Is there a similar doc that I can refer related to prompting a password and where to save it? 

I find the [VSCode encryption](https://jamesbachini.com/how-to-encrypt-text-in-visual-studio-code-vscode/) related to what I'm trying to do. It just that VSCode encrypt the whole file while I just want to encrypt only selected cell.

I'm not sure am I doing it correctly or my method are way off so any suggestion and advice is appreciated.

Thanks,
Adry

**Comment by fcollonval** [comment]
The purpose of this repository is to describe how to use JupyterLab API. As this request is about adding not existing feature, it will be closed. But you can definitely ask on the [Gitter chat](https://gitter.im/jupyterlab/jupyterlab) or on the [Jupyter forum](discourse.jupyter.org/) for pointers.
