### ISSUE TITLE
Tutoral how to add new command in the menu under an existing category

### ISSUE THREAD

**Issue by pacospace** [jupyterlab/extension-examples#168]
### Problem

I'm working on a jupyterlab-extension for dependency management [1]. Some users requested feature to delete kernels directly from the UI, instead of going to the terminal, so the following solution was introduced:

![preview](https://user-images.githubusercontent.com/27498679/124718150-192b5480-df06-11eb-9118-c53e8dc26d01.gif)

I did not find a way to add the new command `Kernel Delete...` to the menu under Kernel, as I think that should be the place.

### Proposed Solution

* Have an example on how to add command to menu on existing category.

### Additional context
* [1] https://github.com/thoth-station/jupyterlab-requirements

**Comment by NoobMaster1999** [comment]
I want to solve this issue. Can anyone please assign me the issue..???

**Comment by fcollonval** [comment]
Thanks for proposing your help. I'm unsure this requires a new example. The _launcher_ example is adding an entry to the `File>New` submenu:

https://github.com/jupyterlab/extension-examples/blob/92e08148a59ee18420cdc22abff279f52d15cc8c/launcher/src/index.ts#L88

Basically you have to use the accessors of [`IMainMenu`](https://jupyterlab.readthedocs.io/en/stable/api/classes/mainmenu.mainmenu-1.html). Moreover in JupyterLab 3.1 a new mechanism to define menu from settings has been introduced. The menu example will be updated in #181.

if you want to help, I can provide you some pointer for #134, #138 or #154.

**Comment by pacospace** [comment]
Thanks @fcollonval !!
