### ISSUE TITLE
update playwright to 1.13

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/extension-examples#177]
Can we update playwright to 1.13 so we can use the drag and drop functionality?

https://github.com/hbcarlos/extension-examples/blob/21d082a23f99a628fe52c560892f3d380ed9eb8f/documents/ui-tests/tests/documents.spec.ts#L67-L71

_Originally posted by @hbcarlos in https://github.com/jupyterlab/extension-examples/issues/163#issuecomment-891776674_

**Comment by hbcarlos** [comment]
Thanks! I'll do it!
