### ISSUE TITLE
mime-renderer example ?

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlab/extension-examples#195]
It would be good to have a mimerender extension example too.  

I tried to use the [mimerender-cookiecutter-ts](https://github.com/jupyterlab/mimerender-cookiecutter-ts), but it breaks right at the initial `pip install -e`.  
Cf. issue [mimerender-cookiecutter-ts/issues/30](https://github.com/jupyterlab/mimerender-cookiecutter-ts/issues/30)

I tried the [hello-world](https://github.com/jupyterlab/extension-examples/tree/master/hello-world) from this repo and it works fine.  
But I could not patch the mimerender-cookiecutter-ts to make it work using the hello-world example...

**Comment by timkpaine** [comment]
@oscar6echo here is a non-ts mime render extension for csv, json, and adding a new `.arrow` type. It is relatively minimal if you ignore the perspective-specific stuff
https://github.com/finos/perspective/blob/master/packages/perspective-jupyterlab/src/js/renderer.js

**Comment by oscar6echo** [comment]
@timkpaine thx for the answer.

After some experiments, I made one, which I share for reference.
https://github.com/oscar6echo/jupyterlab-graphviz
(not published yet on PyPi)

I'll take advantage of this issue to ask some questions so that I can fine tune the implementation:
+ In its current form the extension has some config variables (hover activation and colors): How could I make them available to user config ?
+ This extension uses a `.wasm` file which I add with `package.json/scripts/cpwasm`: Is there a more industrial way to add files in the labextension not managed by webpack ?
+ I show 3 buttons: Is there jupyterlab CSS that I can/should reuse ?
+ Generally did I break any convention or make obvious mistakes: Please let me know !

I would be grateful for any feedback/hints/pointers.

**Comment by fcollonval** [comment]
Thanks for sharing @oscar6echo 

> I'll take advantage of this issue to ask some questions so that I can fine tune the implementation:
> 
>     * In its current form the extension has some config variables (hover activation and colors): How could I make them available to user config ?

That one is gonna be more tricky. You will need to define user settings see [that example](https://github.com/jupyterlab/extension-examples/tree/master/settings). Then you will need to set those settings to all newly created widget and existing one (if the settings changes). To do that, the easiest will be to track all generated widgets currently in the app and the creation of new widgets.

This will require a standard plugin in addition to the mimeextension. And its activate function will need the tokens `IDocRegistry` and `ISettingsRegistry`.

Roughly it will look like

```ts
activate(app, docregistry, settingsregistry): {
   // Create a tracker
   const tracker = new WidgetTracker<GraphvizWidget>({ namespace: /* unique id */ })

   // get your factory
   factory = docregsitry.getWidgetFactory('graphviz-dot viewer');

  settingsregistry.load(/* your plugin settings */).then(settings => {
   const onSettingsChanged = () => {
     // Update the settings on each widget
     tracker.forEach(widget => {
      widget.setConfig(settings.composite);
    });
   }
   settings.changed.connect(onSettingsChanged);
   // get your factory
   factory = docregsitry.getWidgetFactory('graphviz-dot viewer');
   factory.widgetCreated.connect((sender, widget) => {
          // Set the config on the widget
          widget.setConfig(settings.composite);

          void tracker.add(widget);
        });
  });

}
```

>     * This extension uses a `.wasm` file which I add with `package.json/scripts/cpwasm`: Is there a more industrial way to add files in the labextension not managed by webpack ?

After some googling, it seems you could use of the [copy webpack plugin](https://webpack.js.org/plugins/copy-webpack-plugin/). See the JupyterLab documentation to customize the [webpack configuration](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#custom-webpack-config).

>     * I show 3 buttons: Is there jupyterlab CSS that I can/should reuse ?

We are working on https://github.com/jupyterlab-contrib/jupyter-ui-toolkit. It is stable enough for use but not yet enough for migrating JupyterLab core.

>     * Generally did I break any convention or make obvious mistakes: Please let me know !

Nothing obvious from my quick look

**Comment by oscar6echo** [comment]
@fcollonval thx again for this wealth of info !

**Comment by oscar6echo** [comment]
I made another one to display a `.csv` file as an [aggrid](https://www.ag-grid.com/), with default reasonable options.   
https://github.com/oscar6echo/jupyterlab-aggrid

(Because the typescript is highly configurable, it is meant to be adjusted for custom jupyterlite deployments, really)


So another quick question:
+ I hard coded the theme to dark ([here](https://github.com/oscar6echo/jupyterlab-aggrid/blob/a3d5bab8322aeb943048326a5e2b83b23f8ab72d/src/index.ts#L34) and [there](https://github.com/oscar6echo/jupyterlab-aggrid/blob/a3d5bab8322aeb943048326a5e2b83b23f8ab72d/src/index.ts#L117)).  Instead can I import the relevant CSS and set the relevant class based on the current jupyterlab theme ? Is so, how to access it in [index.ts](https://github.com/oscar6echo/jupyterlab-aggrid/blob/main/src/index.ts) ?

**Comment by fcollonval** [comment]
> I made another one to display a `.csv` file as an [aggrid](https://www.ag-grid.com/), with default reasonable options. https://github.com/oscar6echo/jupyterlab-aggrid

thanks for sharing :100: 

> can I import the relevant CSS and set the relevant class based on the current jupyterlab theme ? Is so, how to access it in [index.ts](https://github.com/oscar6echo/jupyterlab-aggrid/blob/main/src/index.ts) ?

The question was raised earlier in an issue; there the [recommended way](https://github.com/jupyterlab/jupyterlab/issues/12449#issuecomment-1111799441) using `MutationObserver` is described.

**Comment by oscar6echo** [comment]
@fcollonval thx again :+1:  
I slightly [adjusted](https://github.com/oscar6echo/jupyterlab-aggrid/blob/2cc67625759059edcb5256fc5876f55cce9327ec/src/index.ts#L121) the jupyterlab-aggrid mime-renderer accordingly.

**Comment by fcollonval** [comment]
Closing as we have integrated https://github.com/jupyterlab/jupyterlab-mp4 as part of JupyterLab 4 upgrade
