### ISSUE TITLE
KernelOutput KernelMessaging Example not working!!

### ISSUE THREAD

**Issue by superjcd** [jupyterlab/extension-examples#196]
## Description
Several examples didn't work, The browser is just not showing  any thing,  insted  came up with  a greyed-out looking like below:
![image](https://user-images.githubusercontent.com/25010312/173006539-a04bf5cf-79e7-4fe4-81b2-54c3e74801b7.png)
And those not working examples(including datagrid example, kernel messaging, kernel output) all used the StackPannel  as the widget, wondering if it related.

## Reproduce
Take [kernel output](https://github.com/jupyterlab/extension-examples/tree/master/kernel-output) for instance, just download the codes, and built the extension, cuz my node version seems not compatible, i used `jlpm install --ignore-engines` to install some dependencies. 

## Context

- Operating System and version: windows10
- Browser and version: 102
- JupyterLab version: 3.4.2

## Browser Output
Console report the following error repeatly, dont know if related to this problem
![image](https://user-images.githubusercontent.com/25010312/173008507-43afe153-a2ef-464a-b168-b98ab5bdb2bb.png)

**Comment by superjcd** [comment]
收到了，谢谢

**Comment by superjcd** [comment]
Recently I found that's not a problem caused by StackPannel, instead it's may caused by SimplifiedOutputArea I guess; And I found a related [issue](https://github.com/jupyter-widgets/ipywidgets/issues/2926),

**Comment by superjcd** [comment]
Ok, I figured it out, just add the widget to the left or right side; StackPannel seems cannot add to the main area directly now!

**Comment by fcollonval** [comment]
Closing as resolved in #225
