### ISSUE TITLE
How to trust HTLM files by default ?

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlab/extension-examples#200]
For info in case somebody is looking for an example of a slight change in the default behavior of an existing extension.

See https://github.com/oscar6echo/jupyterlab-trust-html

Based on conversation in [Jupyterlite issue #708](https://github.com/jupyterlite/jupyterlite/issues/708)

**Comment by fcollonval** [comment]
Thanks for sharing @oscar6echo

**Comment by oscar6echo** [comment]
Now I am trying to make it a native jupyterlab htmlviewer-extension param.  
See https://github.com/jupyterlab/jupyterlab/issues/12792.

**Comment by oscar6echo** [comment]
Done in PR https://github.com/jupyterlab/jupyterlab/pull/12868
