### ISSUE TITLE
Migrate the examples to `hatch`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/extension-examples#210]
### Problem

To follow the lead of the cookiecutter: https://github.com/jupyterlab/extension-cookiecutter-ts/pull/222

And streamline all the examples.

### Proposed Solution

Maybe the upgrade script would work with this and help do most of the work.

### Additional context

https://github.com/jupyterlab/extension-cookiecutter-ts/pull/222

https://blog.jupyter.org/packaging-for-jupyter-in-2022-c7be64c38926

**Comment by fcollonval** [comment]
Closing as done as part of JupyterLab 4 migration

**Comment by jtpio** [comment]
Ah really cool, thanks!
