### ISSUE TITLE
Invaild choice: "--use-feature=in-tree-build" when using the pip verison 23.0.1

### ISSUE THREAD

**Issue by Max-ChenFei** [jupyterlab/extension-examples#219]
Remove the choice of the command in `--use-feature=in-tree-build` in the package.json.

[reference](https://pip.pypa.io/en/stable/news/#v21-3)
>In-tree builds are now the default. --use-feature=in-tree-build is now ignored.

**Comment by fcollonval** [comment]
Hey @Max-ChenFei would you mind providing more context on this issue. When are you seeing the error? What is your environment setup (OS, versions)?

**Comment by Max-ChenFei** [comment]
Hi, just follow the ReadMe to build all the examples.

```
jlpm
jlpm build-ext
```
## Expected behavior
Remove the choice of the command in --use-feature=in-tree-build in the package.json.



## Context



- Operating System and version: Windows 10 
- JupyterLab version: 
- Node.js: 16.17.1
- Python: 3.11
- Pip 23.0.1
