### ISSUE TITLE
Please add a cell toolbar example

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlab/extension-examples#227]
There is a well-known example, https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar. It is cool, but it seems too complicated.
Can you provide a simple example, which may use '@jupyterlab/cell-toolbar'?
1. Some buttons may be available for Code cell only.
2. Some buttons may be available for Markdown cell only.
3. Some buttons may be enabled for some kind of content.

**Comment by psychemedia** [comment]
@MRYingLEE I'm not sure if this is useful, but I posted some notes of my own that occurred to me whilst building a simple notebook toolbar button extension: https://blog.ouseful.info/2023/06/22/updating-the-empinken-extension-from-jupyterlab-3-x-to-4-x/

**Comment by jtpio** [comment]
Thanks @MRYingLEE for opening the suggestion :+1: 

Yes having such example would be great.

**Comment by jtpio** [comment]
cc @brichet who I think was looking into this recently.

**Comment by brichet** [comment]
Thank you for the reminder @jtpio :smile:

**Comment by brichet** [comment]
@jtpio, any opinion about adding a new example or extending to the current *toolbar-button* example ?

**Comment by jtpio** [comment]
Maybe a new one for simplicity, so the example focuses on extending the cell toolbar only? It might also be easier to find from the top-level folder or readme.
