### ISSUE TITLE
Trying to run examples - warnings and errors in TL:DR first build process

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/extension-examples#237]
Trytin to ruyn examples, following the [TL:DR](https://github.com/jupyterlab/extension-examples#tldr). I found I had to do the following to make the errors go away and get a build of the `toolbar-button` demo to build:

```bash
npm install
npm install --save-dev jest ts-jest
pip install --upgrade hatchling
```

I assume there is also a prior requirement to that of getting a recent version on node installed.

**Comment by fcollonval** [comment]
Thanks @psychemedia 

I open #238 to fix this - it removes `types: ["jest"]` in `tsconfig.json`.
