### ISSUE TITLE
The example of documents extension not work

### ISSUE THREAD

**Issue by Jad2wizard** [jupyterlab/extension-examples#253]
## Description
I can open the `documents/testfiles/test.example` and drag the rect cell. But the move of two rectangles cannot be synchronized.
When I print the drive which is the thrid args of the activate function, I got `null`. I think this maybe the reason.

## Reproduce

1. Go to 'extension-examples/documents'
2. Run `jupyter labextension develop . --overwrite`
3. Go to `extension-examples/documents/testfiles/`
4. Run `jupyter lab`

## Context

- Operating System and version: macOS 10.15.7
- Browser and version: Chrome 118.0
- JupyterLab version: 4.0.6

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment]
Hey @Jad2wizard 

I'm not exactly sure what you tried. But if you want to see collaboration (aka document state synchronization) between two clients. You will need to install `jupyter-collaboration`.

**Comment by Jad2wizard** [comment]
Thank you. 
That's work.
