### ISSUE TITLE
server-extension not picking up changes

### ISSUE THREAD

**Issue by ghost** [jupyterlab/extension-examples#260]
Okay, I am not sure if it's a bug or my lack of knowledge, so apologies upfront.

Usually we restart kernel to jupyterlab to pick up changes in our python packages, however in case of server-extension sample there is no kernel and when I make changes to requests, they are not picked up with browser refresh. My solution is running `jupyter lab` again. I did install it in editable mode tho as on Readme file. 

Could you please tell me how can I have my server-extension python changes working without re-running `jupyter lab`?

**Comment by fcollonval** [comment]
It is not possible.

**Comment by jtpio** [comment]
Maybe using the `--autoreload` flag when starting JupyterLab can slightly help? I was added to Jupyter Server in https://github.com/jupyter-server/jupyter_server/pull/380.

Although it's more or a less equivalent to stopping JupyterLab and running `jupyter lab` again.

**Comment by joaopalmeiro** [comment]
Hi! 👋 

Just to complement, if that's okay, I currently launch JupyterLab via `jupyter lab --autoreload --no-browser` to facilitate my workflow when developing server extensions. 

I think it would be interesting to document this command (or a similar one). What do you think?

**Comment by jtpio** [comment]
> I think it would be interesting to document this command (or a similar one). What do you think?

Sure, if you feel like opening a PR please do, thanks!

**Comment by fcollonval** [comment]
Closing as fixed
