### ISSUE TITLE
question: how to enable configuration for server extension

### ISSUE THREAD

**Issue by micahjsmith** [jupyterlab/extension-examples#91]
Thanks for the great collection of examples. I'm writing a server extension, building off the server extension example in this repo, and I am trying to figure out the best way to allow users to provide configuration for my extension.

Options I can think of:
1. rolling my own configuration, i.e. load some random file like `~/.myapp` or using environment variables
2. using `jupyter-config/extension-name.json` or `.py` analogue
3. tying into jupyter lab configuration system, i.e. `~/.jupyter/jupyter_notebook_config.py`

From what I have seen so far, 
1. this always works but it is not user-friendly
2. seems like this can only be used to enable/disable extension but not to configure it
3. seems like it is not possible to add `c.MyApp.some_setting` to the config file unless `MyApp` is in `notebook.NotebookApp.classes`

Any thoughts? Happy to also re-post this in the jupyter discourse if it is off-topic. Thanks.

**Comment by fcollonval** [comment]
Hey @micahjsmith,

> Preliminary note: I never did it myself 😉 

There is an example of configurable server extension in [jupyterlab-github](https://github.com/jupyterlab/jupyterlab-github). More precisely you need to define a class that inherits from [`traitlets.config.Configurable`](https://traitlets.readthedocs.io/en/stable/config.html):

https://github.com/jupyterlab/jupyterlab-github/blob/065aa4429b5cef93a912f9c5e64b138989ff15f2/jupyterlab_github/__init__.py#L19

I quickly installed that extension to play around. And as for the other server options, you could either set it in a Python script, in JSON or with CLI arguments:

```sh
jupyter lab --GitHubConfig.access_token="mydummytoken"
```
```

**Comment by micahjsmith** [comment]
Thank you! This worked for me :)

The keys were to both inherit from `Configurable` and also realize that `APIHandler` has `config` as an attribute that can be passed to the configurable to get around the limitation in point 3.

```py
class MyConfigurable(Configurable): pass

class MyAPIHandler(APIHandler):
    def get(self):
        configurable = MyConfigurable(config=self.config)
```
