### ISSUE TITLE
setting can not use isToggled

### ISSUE THREAD

**Issue by chengyumeng** [jupyterlab/extension-examples#92]
when I install https://github.com/jupyterlab/extension-examples/tree/master/settings,`isToggled` is not useful.

JupyterLab version:2.0.0

**Comment by fcollonval** [comment]
Hey, what are you trying to achieve? 

The purpose of this repository is not to provide useful extensions; just working code for developers to help them understanding the API of JupyterLab.

**Comment by chengyumeng** [comment]
i write a extension to change private settings，but can not use isToggled with JupyterLab 2.0.0.

I think it may be a bug.

**Comment by fcollonval** [comment]
`isToggled` is only for visual effect for the user. The associate value or function should provide a boolean with the toggled status: 

https://github.com/jupyterlab/extension-examples/blob/01f363a6e726f5ca45c83e09c554581b58fee0d1/settings/src/index.ts#L59

When the user click on a toggable menu item, the `execute` function of the associated command is called (as for any menu item). The code impacting the toggle state should be executed there. In the example:

https://github.com/jupyterlab/extension-examples/blob/01f363a6e726f5ca45c83e09c554581b58fee0d1/settings/src/index.ts#L62

**Comment by chengyumeng** [comment]
well，I mean that when flag is true，the item can not be checked in JupyterLab 2.0.0，and JupyterLab 1.2.6 is ok，may be you can have a try.

**Comment by fcollonval** [comment]
I tested it with success on the latest version 2.1.1 - you can do this by launching the example on binder (see badge at the top of the [README](https://github.com/jupyterlab/extension-examples) file). Could you update to it?

**Comment by chengyumeng** [comment]
yeah，fixed

**Comment by telamonian** [comment]
There was a bug in jlab 2.0.x whereby the check icons were broken for some submenus and some menus supplied by 3rd party extensions. The underlying `isToggled` logic worked just the same, though (ie a CSS class gets added or removed depending on the value returned by the `isToggled` callback).

In any case the check icon bug was fixed as of jlab 2.1.0

**Comment by fcollonval** [comment]
Thanks @telamonian for providing the background issues (that I missed 😞)
