### ISSUE TITLE
Add an example for toolbar menu

### ISSUE THREAD

**Issue by rahulpshah** [jupyterlab/extension-examples#98]
Hello everyone, I am trying to create an extension that tries to add an item to the default toolbar menu in the NotebookPanel. I have tried to look at similar extensions like `jupyterlab-git` to see how they implement it but have found myself unsuccessful. I would like to contribute to this repository with a little bit of help. My questions are around how to access the defaultToolbar (https://github.com/jupyterlab/jupyterlab/blob/f0153e0258b32674c9aec106383ddf7b618cebab/packages/notebook/src/default-toolbar.tsx) and how to add items to it.

**Comment by fcollonval** [comment]
Hey @rahulpshah thanks for the proposition. The feature you are speaking of is in fact in `nbdime`. You can look at that file to see the code:
https://github.com/jupyter/nbdime/blob/master/packages/labextension/src/plugin.ts

There is also a simpler example (but the code is for a quite old version of JupyterLab):
https://github.com/jupyterlab/runall-extension

Don't hesitate to start a PR with status Work In Progress (WIP) to get help from us.

**Comment by SonakshiGrover** [comment]
@fcollonval  I have a similar question. Could you please look at this [8873](https://github.com/jupyterlab/jupyterlab/issues/8873)

**Comment by yash112-lang** [comment]
Hello @rahulpshah, is this issue is still open. I want to work on this issue. I am new to open source and want to contribute.

**Comment by fcollonval** [comment]
@yash112-lang this is still open. It will be wonderful if you could push a PR with such example. Let me know if you need more pointers than those given in the above comment.

**Comment by yash112-lang** [comment]
Can you please elaborate the problem a little more, so that I can start working on this?

**Comment by fcollonval** [comment]
> Can you please elaborate the problem a little more

Sure

The goal of this repository is to host working examples focusing on a feature of JupyterLab. The idea to solve this one is to create a new extension (starting from the [cookiecutter template](https://github.com/jupyterlab/extension-cookiecutter-ts/)) that adds one button to the notebook toolbar and explains the needed code.

For example, you could add a button that clears all outputs (command named `'notebook:clear-all-cell-outputs'`).

You can take inspiration from that code: https://github.com/jupyterlab/runall-extension/blob/master/src/index.ts.

> Open the PR quickly even if the code does not work. So we can help you going through any problems you encounter.

**Comment by yash112-lang** [comment]
shall I add a button in **`Run`** that clears all output?

**Comment by fcollonval** [comment]
The idea is to add a button that will trigger the _clear all output_ action in the green area shown below:

![image](https://user-images.githubusercontent.com/8435071/121908592-71b76980-cd2d-11eb-8494-71b90eafbd28.png)

**Comment by yash112-lang** [comment]
I created a button where you described but currently, it only alerts what it does. I opened the **pull request** for it. Now how do I add functionality to it? It's my first PR so if there are any mistakes let me know.
![image](https://user-images.githubusercontent.com/56151779/122044462-2ae37580-cdfa-11eb-9f77-e3a543333a1a.png)

**Comment by fcollonval** [comment]
Awesome :tada: I'll comment on the PR from now one as it will be easier to place comment in the code.

**Comment by fcollonval** [comment]
Fixed by #162
